from enum import StrEnum


class KubeClientAuthType(StrEnum):
    NONE = "none"
    TOKEN = "token"
    CERTIFICATE = "certificate"


DEFAULT_AUTH_TYPE = KubeClientAuthType.NONE
DEFAULT_TOKEN_UPDATE_INTERVAL = 300
DEFAULT_CLIENT_CONN_TIMEOUT = 300
DEFAULT_CLIENT_READ_TIMEOUT = 300
DEFAULT_CLIENT_WATCH_TIMEOUT = 1800
DEFAULT_CLIENT_CONN_POOL_SIZE = 300

DEFAULT_TIMEOUT = 10.0 * 60  # 10 minutes
DEFAULT_WAIT_INTERVAL = 1.0  # 1 second
