name: CI

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 4 * * *
jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: ['3.13']
    steps:
    - name: Checkout commit
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.py_version }}
    - name: Cache packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py-${{ matrix.py_version }}-${{ hashFiles('pyproject.toml') }}
    - name: Install poetry
      run: pip install poetry==2.0.1
    - name: Install dependencies
      run: make setup
    - name: Lint
      env:
        CI_LINT_RUN: 1
      run: |
        echo "::add-matcher::.github/actionlint-matcher.json"
        make lint
    - name: Run unit tests
      run: make test_unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: .coverage.xml
        flags: py${{ matrix.py_version }}
        name: codecov
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-3.13-${{ hashFiles('pyproject.toml') }}
      - name: Install poetry
        run: pip install poetry==2.0.1
      - name: Install dependencies
        run: make setup
      - name: Start minikube
        run: |
          make install_k8s
          make start_k8s
      - name: Setup services in minikube
        run: make apply_configuration_k8s
      - name: Run integration tests
        run: make test_integration

  check: # This job does nothing and is only used for the branch protection
    name: Check
    needs: [unit_tests, integration_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo "All checks have passed"

  approve:
    name: Approve bot PR
    runs-on: ubuntu-latest
    if: endsWith(github.actor, '[bot]')
    needs: check
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: metadata
      id: metadata
      if: github.actor == 'dependabot[bot]'
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Enable auto-merge for bot PRs
      run: gh pr merge --auto --squash --delete-branch "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Release client
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for trusted publishing & sigstore
    steps:
    - name: Checkout commit
      uses: actions/checkout@v5
    - name: Install python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13
    - name: Install poetry
      run: |
        python -m pip install "poetry==2.0.1"
    - name: Install dependencies
      run: |
        make venv
    - name: Build package
      run: |
        poetry build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.1.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
